print("hi")
print("DEkA")
print(5+5)
print("5+5")
print("bla bla bla")
print("help")
print("i love playing cards")
print("poker")
print("joker")
print("durak")
print("i know russian very good")
print("end i hate it")
print("i have no idea what to print")
print("Nanuka")
print("Mamuka")
print("cocomelon")
print("cry baby magic tears")
print("love maincraft")
print("bobobo")
print("finally")